export const galleryConstants = {
  UPLOAD_IMAGE: 'app/UPLOAD_IMAGE',
  SET_GALLERY: 'gallery/SET_GALLERY',
  DELETE_MOVIE: 'gallery/DELETE_MOVIE',
  DELETE_SCENE: 'gallery/DELETE_SCENE',
  DELETE_ACTOR_FROM_SCENES: 'gallery/DELETE_ACTOR_FROM_SCENES',
  UPDATE_ACTOR_PROFILE_PHOTO: 'gallery/UPDATE_ACTOR_PROFILE_PHOTO',
};
